metric: true
actionbarMoney: true #Should the onMoneyReceive message be displayed on the actionbar?

Message:
  Command:
    reload: "&7/drop reload - &2Reload the configs"
    onReload: "&2Plugin succesfully reloaded"
    reloadFailed: "&4Something went wrong on plugin reload"
  Normal:
    onMoneyReceive: "&2&l+%money%"