name: HopeDrop
version: 1.22
main: me.parozzz.hopedrop.HopeDrop
author: Parozzz
commands:
  hopedrop:
    aliases: [drop, hpd]
    Usage: /drop
    Description: Main plugin command
softdepend: [Vault]